# Algebra Linear

In [1]:
import numpy as np

In [2]:
A = np.array(([1,2,3],[4,5,6],[7,8,9]))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Podemos usar o método .matrix()
B = np.matrix(([1,2,3],[4,5,6]))
B

matrix([[1, 2, 3],
        [4, 5, 6]])

#### Tipos de Matrizes

In [4]:
# Matrix Diagonal e Triangular
# Matriz quadrada quando o tamanho das linhas for igual ao tamanho das colunas: m = n.

# Diagonal: Somente quando os valores da diagonal são > 0.
D = np.diag([1,5,7,9,10,1])
D

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  1]])

In [5]:
# Matriz Quadrada Superior: Quando os elementos abaixo da diagonal principal são todos = a 0.
QS = np.array(([5,6,0],[0,3,2],[0,0,1]))
QS

array([[5, 6, 0],
       [0, 3, 2],
       [0, 0, 1]])

In [6]:
# Matriz Quadrada Inferior: Quando os elementos acima da diagonal principal são todos = a 0.
QI = np.array(([1,0,0],[5,6,0],[1,3,2]))
QI

array([[1, 0, 0],
       [5, 6, 0],
       [1, 3, 2]])

In [7]:
# Matriz Linha.
L = np.array([[2,4,6]])
L

array([[2, 4, 6]])

In [8]:
# Matriz Coluna.
C = np.array([[2],[-4],[6],[-10]])
C

array([[  2],
       [ -4],
       [  6],
       [-10]])

In [9]:
# Modo diferente para criar uma Matriz Coluna.
Dt = np.transpose([[2,-4,6,-10]])
Dt

array([[  2],
       [ -4],
       [  6],
       [-10]])

In [10]:
# Matriz Nula: Todos os elementos são = a 0.
N = np.zeros([2,2])
N

array([[0., 0.],
       [0., 0.]])

In [11]:
# Matriz Identidade: Todos os valores da diagonal principal são = a 1.
I = np.array([[1,0,0],[0,1,0],[0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
# Criando uma Matriz Identidade com o método .identity().
MI = np.identity(3)
MI

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Matriz Transposta: Troca linhas por colunar ou vice-versa.
M = np.array([[1,0,3],[2,1,4]])
M

array([[1, 0, 3],
       [2, 1, 4]])

In [14]:
MT = np.transpose(M)
MT

array([[1, 2],
       [0, 1],
       [3, 4]])

In [15]:
# Outra forma de 'criar' uma Matriz Transposta com o método .T.
A = np.array([[1,0,3],[2,1,4]])
AT = A.T
AT

array([[1, 2],
       [0, 1],
       [3, 4]])

In [16]:
# Multiplicação entre Matrizes.
M1 = np.array([[1,2,3,4]])
M2 = np.array([[20,30,40,50]])

M3 = M1 * M2
M3

array([[ 20,  60, 120, 200]])

In [17]:
M4 = np.dot(np.transpose(M1),M2) # É necessario pq o número de linhas de M1 é diferente do número de colunas de M2.
M4

array([[ 20,  30,  40,  50],
       [ 40,  60,  80, 100],
       [ 60,  90, 120, 150],
       [ 80, 120, 160, 200]])

#### Traço da Matriz
- Traço de uma matriz quadrada é definido como a soma dos elementos de  sua diagonal principal.
  - Quando a matriz não é quadrada, somamos os elementos que fazem parte de uma diagonal principal.

In [18]:
A = np.array(([1,1],[2,2]))
B = np.array(([1,1,1], [3,3,3]))

tr_A = np.trace(A)
tr_A

3

In [19]:
tr_B = np.trace(B)
tr_B

4

#### Matriz Inversa
- Seja A uma matriz [m X n], esta matriz é dita invertível ou não singular se existe uma matriz B que satisfaça a seguinte condição abaixo:
  - AB = BA = Iⁿ - (Iⁿ é a matriz identidade) 

In [20]:
from numpy.linalg import inv

In [21]:
A = np.array(([1,2],[3,4]))
B = inv(A) # Calcula a inversa de A.
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
# Verificar B como inversa da matriz A.
np.dot(B,A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [16]:
# ou

In [23]:
B.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

#### Propriedades da Matriz Inversa

In [24]:
A = np.array(([1.,2.],[3.,4.]))

In [25]:
# Se A seja uma matriz inversa, então A⁻¹ também é invetível: (A⁻¹)⁻¹ = A.
Ai = inv(inv(A)) # Se fizermos [inv(inv(A)) == A] dara falso por conta dos arredondamentos.
Ai               # Contudo Ai é igual a A.

array([[1., 2.],
       [3., 4.]])

In [26]:
# Caso A e B forem matrizes invertíveis, então AB também é invertível.
B = inv(A)
I = inv(A.dot(B))

I

array([[ 1.0000000e+00,  0.0000000e+00],
       [-8.8817842e-16,  1.0000000e+00]])

In [27]:
V = inv(B).dot(inv(A))
V

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [28]:
# Se A é uma matriz invertível, então a seguinte relação é válida.
X1 = inv(A.T)
X1

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [29]:
T1 = (inv(A)).T
T1

array([[-2. ,  1.5],
       [ 1. , -0.5]])

### Manipulando Elementos da Matriz

In [30]:
A = np.array(([1,2,3,4],[5,6,7,8],[9,10,111,12]))
A

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 111,  12]])

In [31]:
# Pegando o elemento A(1,1).
a11 = A[0,0]
a11

1

In [32]:
# Pegando a 1° linha.
A1n = A[0,:]
A1n

array([1, 2, 3, 4])

In [33]:
# Pegar a 2° coluna.
Am2 = A[:,1]
Am2

array([ 2,  6, 10])

## Sistema de Equações Lineares
- Sistemas lineares são ótimos para modelar e simplificar problemas do nosso dia a dia.

### Representação Matemática

![Math](sistema-linear.png)

#### Representar matricialmente o sitema acima

![Matriz](matricial.png)

In [34]:
A = np.array(([-1,2],[2,1]))
B = np.array(([-1],[5]))

det_A = np.linalg.det(A)
det_A

-5.000000000000001

In [35]:
A_inv = inv(A)
X = A_inv.dot(B)
X

array([[2.2],
       [0.6]])

In [36]:
# O método .solve() mais rápido e de forma eficiente.
A = np.array(([-1,2],[2,1]))
B = np.array(([-1],[5]))

X = np.linalg.solve(A,B)
X

array([[2.2],
       [0.6]])

### Determinantes de Matrizes
- É um valor numerico que vai representar uma matriz quadrada.

In [37]:
# Calculando o Determinante
from numpy.linalg import det

In [38]:
A = np.array(([1,2,4],[5,3,-1],[7,2,0]))
det_A = det(A)

det_A

-56.00000000000002

In [39]:
# Outro teste.
B = np.array(([1,2,4,5,6,7],[5,3,-1,5,1,2],[7,2,0,1,4,9]))
B

array([[ 1,  2,  4,  5,  6,  7],
       [ 5,  3, -1,  5,  1,  2],
       [ 7,  2,  0,  1,  4,  9]])

In [40]:
det(B) # Vai dar erro pq, o determinante só pode ser calculado em matrizes quadradas.

LinAlgError: Last 2 dimensions of the array must be square

In [41]:
# Calculando em uma matriz maior.
C = np.array(([1,2,4,5,6,7],[5,3,-1,5,1,2],[7,2,0,1,4,9],[1,2,1,5,6,5],[-7,2,4,-1,6,6],[0,2,5,5,9,7]))
C

array([[ 1,  2,  4,  5,  6,  7],
       [ 5,  3, -1,  5,  1,  2],
       [ 7,  2,  0,  1,  4,  9],
       [ 1,  2,  1,  5,  6,  5],
       [-7,  2,  4, -1,  6,  6],
       [ 0,  2,  5,  5,  9,  7]])

In [42]:
D = det(C)
D

8184.000000000006

## Autovalores e Autovalores

### Transformação Linear

In [48]:
# Autovalores e Autovetores
import numpy.linalg as al
A = np.array(([4,2,0],[-1,1,0],[0,1,2]))
autovalores, autovetores = al.eig(A)

In [49]:
autovalores

array([2., 2., 3.])

In [50]:
autovetores

array([[ 0.00000000e+00,  4.44089210e-16, -8.16496581e-01],
       [ 0.00000000e+00, -4.44089210e-16,  4.08248290e-01],
       [ 1.00000000e+00,  1.00000000e+00,  4.08248290e-01]])

### Matrizes e Estatísticas

In [52]:
import numpy as np

In [54]:
T = np.array(([6,5,9,6],[8,9,8,7],[9,9,8,6],[7,8,6,9]))
T

array([[6, 5, 9, 6],
       [8, 9, 8, 7],
       [9, 9, 8, 6],
       [7, 8, 6, 9]])

In [63]:
# Mantendo as colunas fixas e coletar todas as linhas.
med_logica  = T[:,0].mean()
med_calculo = T[:,1].mean()
med_python  = T[:,2].mean()
med_ingles  = T[:,3].mean()

media_turma = [med_logica, med_calculo, med_python, med_python]
media_turma

[7.5, 7.75, 7.75, 7.75]

In [59]:
# Mantendo as linhas fixas e coletando as colunas.
med_A = T[0,:].mean()
med_B = T[1,:].mean()
med_C = T[2,:].mean()
med_D = T[3,:].mean()

media_notas = (med_A, med_B, med_C, med_D)
media_notas

(6.5, 8.0, 8.0, 7.5)

In [69]:
media_faculdade = T.mean() # Média
media_faculdade

7.5

In [71]:
desvio_padrao = T.std() # Desvio padrão
desvio_padrao

1.3228756555322954